FROM node:20-alpine AS builder
WORKDIR /app
COPY public/package*.json ./
RUN npm install

FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY public/ /usr/share/nginx/html
COPY --from=builder /app/node_modules /usr/share/nginx/html/node_modules

EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]