services:
  #frontend container (NGINX)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #https certificates
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - artigianato-network

  #backend container (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
      - microservice_users
      - microservice_images
      - microservice_products
      - microservice_purchases
      - microservice_tickets
    networks:
      - artigianato-network
    volumes:
      - ./certs:/certs:ro

  #database container (PostgreSQL)
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace-artigiani
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "@MkpArt25FL#"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistenza dei dati del database
    ports:
      - "5432:5432"
    networks:
      - artigianato-network

  #microservices
  microservice_users:
    build:
      context: ./microservices
      dockerfile: Dockerfile.microservices
      args:
      - SERVICE_NAME=users
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./certs:/certs:ro
  
    depends_on:
      - db
    networks:
      - artigianato-network
    
  microservice_images:
    build:
      context: ./microservices
      dockerfile: Dockerfile.microservices
      args:
        - SERVICE_NAME=images
    volumes:
      - images_uploads:/app/uploads
      - ./certs:/certs:ro
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - artigianato-network
      
  
  microservice_products:
    build:
      context: ./microservices
      dockerfile: Dockerfile.microservices
      args:
        SERVICE_NAME: products
    volumes:
      - ./certs:/certs:ro
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      - db
    networks:
      - artigianato-network
  
  microservice_purchases:
    build:
      context: ./microservices
      dockerfile: Dockerfile.microservices
      args:
      - SERVICE_NAME=purchases
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./certs:/certs:ro
  
    depends_on:
      - db
    networks:
      - artigianato-network

  microservice_tickets:
    build:
      context: ./microservices
      dockerfile: Dockerfile.microservices
      args:
        SERVICE_NAME: tickets
    volumes:
      - ./certs:/certs:ro
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      - db
    networks:
      - artigianato-network

volumes:
  db_data:
  images_uploads:

networks:
  artigianato-network:
    driver: bridge
