services:
  #frontend container (NGINX)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #nginx configuration
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/public:/usr/share/nginx/html:ro
      #https certificates
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - artigianato-network

  #backend container (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:@MkpArt25FL#@db:5432/marketplace-artigiani
    depends_on:
      - db
    networks:
      - artigianato-network

  #database container (PostgreSQL)
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace-artigiani
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "@MkpArt25FL#"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistenza dei dati del database
    ports:
      - "5432:5432"
    networks:
      - artigianato-network
  #microservices
  #microservice_users:
  #  build:
  #   context: ./microservices
  #    dockerfile: Dockerfile.microservices
  #    args:
  #      - SERVICE_NAME=users
  #  ports:
  #    - "4001:4001" #microservice port
  #  environment:
  #    DATABASE_URL: postgres://admin:@MkpArt25FL#@db:5432/marketplace-artigiani
  #  depends_on:
  #    - db
  #  networks:
  #    - artigianato-network
volumes:
  db_data:

networks:
  artigianato-network:
    driver: bridge